version: '3.8'

services:
  # Frontend Next.js (desenvolvimento)
  visagio-frontend:
    build:
      context: ./DEMO
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_RAG_API_URL=http://localhost:8000
    volumes:
      - ./DEMO:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - visagio-dev-network

  # API RAG (desenvolvimento)
  visagio-rag-api:
    build:
      context: ./RAG
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_PATH=${DATABASE_PATH:-Bases_VAI - oficial real.db}
      - API_TITLE=${API_TITLE:-Visagio RAG API}
      - API_VERSION=${API_VERSION:-1.0.0}
      - MODEL_NAME=${MODEL_NAME:-gemini-2.5-flash}
      - TEMPERATURE=${TEMPERATURE:-0.0}
      - SIMILARITY_THRESHOLD=${SIMILARITY_THRESHOLD:-0.7}
    volumes:
      - ./RAG:/app
      - ./RAG/Bases_VAI - oficial real.db:/app/Bases_VAI - oficial real.db
    restart: unless-stopped
    networks:
      - visagio-dev-network

networks:
  visagio-dev-network:
    driver: bridge 