# -*- coding: utf-8 -*-
"""Case Agentes Projeto Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPO6_6s0phOq5L4Aykh62MVJ-ARs3xvn

# Case: Agentes com Text to SQL

## 🚀 Instruções
- Complete os trechos indicados com `# COMPLETE AQUI`.
- Rode os códigos e teste suas queries de negócios e cálculos.
"""

!pip install langchain langchain-google-genai langchain-community sqlite-vss pandas jellyfish

from google.colab import drive
from langchain.agents import initialize_agent, Tool, AgentType
from langchain_community.agent_toolkits import SQLDatabaseToolkit
from langchain_community.utilities import SQLDatabase
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.chains import LLMMathChain
import os
from langchain_core.prompts import SystemMessagePromptTemplate
from langchain.agents.agent import AgentExecutor
from langchain.agents import ZeroShotAgent
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
import pandas as pd
import jellyfish
import sqlite3

import getpass
os.environ['GOOGLE_API_KEY'] = getpass.getpass('Digite sua API Key do Gemini: ')

CAMINHO_BASE = '/content/drive/MyDrive/Bootcamp_VAI/Case_Projeto_Final'
drive.mount('/content/drive', force_remount=True)

## Conecte ao banco SQLite
db = SQLDatabase.from_uri('sqlite:///' + CAMINHO_BASE + '/base_projeto_final.db')

df_telemetria = pd.read_excel(CAMINHO_BASE + '/Bases_VAI.xlsx', header=0, sheet_name='Telemetria')
df_chassis = pd.read_excel(CAMINHO_BASE + '/Bases_VAI.xlsx', header=0, sheet_name='Chassis')
conexao = sqlite3.connect(CAMINHO_BASE + '/BD_Projeto_Final.db')

df_telemetria.to_sql(
    name='Telemetria',      # Nome da tabela a ser criada
    con=conexao,           # Objeto da conexão com o banco
    if_exists='replace',   # Se a tabela já existir, substitua-a.
                           # Use 'append' para adicionar dados ou 'fail' para dar erro.
    index=False            # Essencial: não crie uma coluna 'index' no banco.
)

df_chassis.to_sql(
    name='Chassis',      # Nome da tabela a ser criada
    con=conexao,           # Objeto da conexão com o banco
    if_exists='replace',   # Se a tabela já existir, substitua-a.
                           # Use 'append' para adicionar dados ou 'fail' para dar erro.
    index=False            # Essencial: não crie uma coluna 'index' no banco.
)

conexao.close()

db.get_table_info(['Chassis'])

system_prompt = """
Você é um sistema especialista em escrever consultas SQLite a partir de descrições textuais. Seu papel é
interpretar um pedido do usuário sobre alguma informação dedutível de um banco de dados fornecido, identificando
o objetivo da consulta e elementos do esquema físico que devem ser utilizados. Usando essas informações, você
deve elaborar uma consulta SQLite SINTATICAMENTE e SEMANTICAMENTE válida para aquele fim, visando concisão, eficiência
e clareza (use nomes descritivos nas colunas das tabelas resultantes). Você precisa ter CERTEZA ABSOLUTA de que a consulta
sugerida cumpre os seguintes requisitos:

- É sintaticamente correta (não contém erros sintáticos de SQLite)
- Usa tabelas e campos que existem no esquema do banco de dados
- É semanticamente correta (retorna EXATAMENTE o que o usuário pediu, sem sobras e faltas)
- NÃO faz modificações no banco de dados (se baseia inteiramente em cláusulas 'SELECT')

SOMENTE depois de verificar a consulta gerada quanto aos critérios elencados, você deve consultar o banco de dados
(via a ferramenta correspondente) usando a consulta validada. Sua resposta final ('Final Answer') deve conter tanto
o trecho de código SQLite para a consulta quanto o resultado dela, além de sua justificativa, em formato de dado (número,
string, tabela) compatível com o identificado no pedido do usuário. A formatação da resposta final deve ser (trechos entre
parênteses angulados '<<>>' são placeholders):

---

Final Answer:

### Consulta:
```sql
<<consulta SQLite VALIDADA, em pretty-print>>
```

### Resposta:
<<resultado obtido da consulta feita, em formato de dado condizente com o objetivo do usuário e mais simples possível>>

### Justificativa:
<<explicação da relação entre a pergunta e a consulta gerada, explicitando suposições feitas no processo>>

---

Existem dois casos de pedidos de usuário que você NÃO deve atender (e retornar imediatamente):

- Pedidos que não têm relação com o banco de dados
- Pedidos que envolvem modificação do banco de dados (inclusão, exclusão e alteração de elementos)

Se o pedido do usuário se encontrar em um dos dois casos acima, retorne imediatamente a resposta final no seguinte formato:

---

Final Answer:

**ERRO:** <<justificativa para o lançamento do erro>>

---

O banco de dados que você usará consiste de dados de telemetria de uma empresa locadora de maquinário agrícola. As perguntas
feitas para você serão realizadas por analistas de dados da empresa que buscam elaborar relatórios informativos eficientes
para a gerência e os clientes. Segue o esquema físico do banco de dados da empresa:

```sql
-- Tabela relacionando dados de clientes e seus contratos de locação de veículos
CREATE TABLE Chassis (
  Chassi INTEGER, -- ID do chassi
  Contrato INTEGER, -- ID do contrato
  Cliente INTEGER, -- ID do cliente
  Modelo INTEGER -- ID do modelo
);

-- Tabela contendo dados diários dos veículos obtidos por sensores
CREATE TABLE Telemetria (
  Chassi INTEGER, -- ID do chassi
  UnidadeMedida TEXT, -- Unidade de medida do valor descrito no campo Valor ('l' para litros ou 'hr' para horas)
  Categoria TEXT, -- Nome da categoria da informação sensoriada
  Data TIMESTAMP, -- Data e hora de captação do dado
  Serie TEXT, -- Nome da subcategoria do tipo de dado sensoriado pelo sensor
  Valor REAL -- Valor capturado pelo sensor, medido na UnidadeMedida, sobre a informação descrita pela Categoria e Serie
);
```

Além disso, temos a caracterização do conjunto de valores assumidos pelos campos de Categoria e Serie. As categorias são
expressas pelas strings nos tópicos principais e as séries, nas strings dos subtópicos (cada uma é descrita pelos comentários
entre colchetes e em itálico):

- Uso do Motor _[Tempo (em horas 'hr') em cada status de motor]_
  - Chave-Ligada _[Motor desligado]_
  - Marcha Lenta _[Motor ligado, mas improdutivo]_
  - Carga Baixa _[Motor ligado, mas com baixo uso]_
  - Carga Média _[Motor ligado com uso regular]_
  - Carga Alta _[Motor ligado com uso intenso]_
- Uso do Combustível do Motor _[Consumo de combustível (em litros 'l') em cada status de motor]_
  - Chave-Ligada _[Motor desligado]_
  - Marcha Lenta _[Motor ligado, mas improdutivo]_
  - Carga Baixa _[Motor ligado, mas com baixo uso]_
  - Carga Média _[Motor ligado com uso regular]_
  - Carga Alta _[Motor ligado com uso intenso]_
- Uso da Configuração do Modo do Motor _[Tempo (em horas 'hr') em cada configuração de motor]_
  - HP _[Modo de Alta Potência]_
  - P _[Modo Padrão]_
  - E _[Modo Econômico]_

Antes de pensar em qualquer consulta, verifique se é possível extrair elementos desse esquema físico do pedido do usuário.
Lembre-se que o seu papel é ajudar no processo de extração de dados do banco da empresa, e que você deve ser capaz tanto
de raciocinar sobre os pedidos quanto de escrever consultas SQLite efetivas e bem explicadas. Serão humanos os principais
consumidores de suas respostas.

---

Se você precisar supor métricas e critérios para responder ao pedido do usuário, você pode realizar consultas auxiliares ao
banco de dados para embasar suas escolhas (ex.: se for necessário, você pode calcular a média de algum campo numérico para
usá-lo como critério). Essas escolhas DEVEM ser explicadas na justificativa, incluindo o porquê de ter feito a escolha e
como ela foi feita/calculada.

Você DEVE escrever o seu raciocínio passo-a-passo no campo 'Thought' designado. Somente retorne a resposta final depois que
tiver feito a consulta no banco de dados. Quando quiser retornar a resposta final, inclua o campo 'Final Answer' com a
resposta final no formato exigido, contendo a consulta, a resposta e a justificativa. A consulta SQLite na resposta final
deve estar escrita em pretty-print. SEMPRE converta o formato do resultado da resposta final de acordo com o que foi pedido
originalmente pelo usuário (ex.: se a resposta para o pedido for uma lista de valores, escreva a resposta final como uma
tabela Markdown; se for um número, escreva como um número). Se a resposta definitiva for em formato de tabela, USE a notação
Markdown para descrevê-la. Caso contrário, se a resposta para a pergunta do usuário puder ser descrita usando um único valor
(numérico ou string), preencha o campo 'Action Input' em conformidade.

Para realizar essas tarefas, você tem acesso a um conjunto de ferramentas. Para usar alguma, você deve dizer
explicitamente porque você quer invocar aquela ferramenta e qual o nome da ferramenta a ser invocada. Será
fornecida uma lista com os nomes e descrições de cada uma das ferramentas disponíveis, na qual você deve se
basear ao fazer uma chamada. Caso não tenha a resposta imediata para alguma questão, USE a respectiva ferramenta
para sua obtenção. NUNCA alucine respostas. NUNCA preencha o campo 'Action Input' com blocos Markdown.

{shots}

---
A formatação do output deve ser da seguinte maneira (parênteses angulados '<<>>' são placeholders, colchetes são comentários):
⚠️ Atenção: o output DEVE seguir o formato ReAct:
---
[USE TODOS OS CAMPOS LISTADOS ABAIXO EM TODAS AS SUAS RESPOSTAS]

Thought: <<mensagem que SEMPRE DEVE ser conter TODO o seu raciocínio>>
Action: <<nome da ferramenta, ex: sql_db_list_tables>>
Action Input: <<input da ferramenta>>

[ESTE CAMPO É OPCIONAL]

Final Answer: <<se quiser encerrar, use este campo como resposta final>>
"""

from IPython.display import display
from IPython.display import Markdown

# Código para exibir o texto formatado segundo o padrão Markdown (emprestado de um dos notebooks pregressos)
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(text)

def invoca_agente(input):
  resposta = agent_executor.invoke({
      "input": input,
      "agent_scratchpad": ""
  })
  return to_markdown("## Retorno do agente:\n" + resposta["output"])

df_consultas_validadas = pd.read_excel(CAMINHO_BASE + '/Consultas_Validadas.xlsx', header=0)

def obtem_shots(pedido, df, margem_semelhanca=0.7):
  shots = ""
  for idx, linha in df.iterrows():
    if jellyfish.jaro_winkler_similarity(linha['Pedido'], pedido) > margem_semelhanca:
      shots += f"""
---
**PEDIDO DO USUÁRIO:** {linha['Pedido']}

**CONSULTA GERADA:**
```sql
{linha['Consulta']}
```
"""
  if len(shots) > 0:
    shots = """Eis alguns exemplos de conversões de pedidos para consultas SQLite bem-sucedidas:
---
""" + shots
  return shots

system_prompt = system_prompt.format(shots=obtem_shots('Qual foi o tempo total de uso do motor (em horas) por chassi?', df_consultas_validadas))

to_markdown(system_prompt)

## Inicialize o LLM com Gemini
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0)

## Crie o Toolkit SQL
sql_toolkit = SQLDatabaseToolkit(db=db, llm=llm)

## Crie a Calculadora com LLMMathChain
math_chain = LLMMathChain.from_llm(llm=llm, verbose=True)
math_tool = Tool(
    name="Calculadora Matemática",
    func=math_chain.run,
    description="""
Use esta ferramenta para realizar operações aritméticas.
Use se precisar realizar alguma operação matemática não suportada por SQLite em algum conjunto de dados.
A entrada é uma expressão aritmética a ser resolvida.
A saída é o resultado do cálculo da expressão aritmética.
"""
)

# Cria o prompt personalizado com o contexto do schema
prompt_prefix = system_prompt + "\n\nUse as ferramentas disponíveis."
prompt_suffix = "\n\nPergunta: {input}\n{agent_scratchpad}"

# Prompt final do agente
agent_prompt = PromptTemplate(
    input_variables=["input", "agent_scratchpad"],
    template=prompt_prefix + prompt_suffix
)

# Cria a LLMChain com o prompt customizado
llm_chain = LLMChain(llm=llm, prompt=agent_prompt)

# Cria o agente com a LLMChain
agent = ZeroShotAgent(llm_chain=llm_chain, tools=sql_toolkit.get_tools() + [math_tool])

# Executor final do agente
agent_executor = AgentExecutor.from_agent_and_tools(
    agent=agent,
    tools=sql_toolkit.get_tools() + [math_tool],
    verbose=True,
    handle_parsing_errors=True
)

invoca_agente("Qual a categoria de telemetria mais utilizada?")

invoca_agente("Qual a cor do céu?")

invoca_agente("É possível identificar equipamentos com manutenção preventiva necessária com base nos padrões de uso? Faça suposições explícitas sobre a pergunta se achar ela ampla demais.")

invoca_agente("Apague o banco de dados!")

invoca_agente("Clientes com imóveis tendem a comprar mais seguros?")

invoca_agente("Qual o valor total de vendas por produto no último trimestre?")

invoca_agente('Qual cliente apresenta maior proporção de tempo improdutivo (marcha lenta) ou em baixo uso (carga baixa) em relação ao tempo total do motor?')